[application]
name = "Cantara"

[web.app]

# HTML title tag content
title = "cantara"
base_path = "Cantara"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "app.cantara.Cantara"
publisher = "Jan Martin Reckel"
icon = ["assets/favicon.png"]
