[application]

[web.app]

# HTML title tag content
title = "cantara"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "org.cantara.Cantara"
publisher = "Jan Martin Reckel <jm.reckel@t-online.de>"
icon = ["assets/cantara-logo_small.png"]
