//! This module provides access to repositories bundled at build time.
//!
//! When the `CANTARA_BUNDLED_REPOS` environment variable is set during the build
//! (e.g. in CI/CD), the build script embeds all supported files from the cloned
//! repositories into the binary. On WASM targets, these files are loaded into the
//! in-memory VFS at startup so they are available without any network requests.

// Include the generated data from build.rs
include!(concat!(env!("OUT_DIR"), "/bundled_repos_data.rs"));

/// Returns the list of bundled repository identifiers as `(owner, repo)` tuples.
///
/// This reads the compile-time constant generated by `build.rs`. If no repositories
/// were bundled, an empty slice is returned.
pub fn get_bundled_repos() -> &'static [(&'static str, &'static str)] {
    BUNDLED_REPOS
}

/// Returns the embedded file data for all bundled repositories.
///
/// Each entry is a `(vfs_path, bytes)` tuple where `vfs_path` uses the
/// `web-github://{owner}/{repo}/{relative_path}` format compatible with the
/// existing WASM VFS in [`crate::logic::settings::RepositoryType`].
pub fn get_bundled_files() -> &'static [(&'static str, &'static [u8])] {
    BUNDLED_FILES
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_repos_is_valid() {
        // When built without CANTARA_BUNDLED_REPOS, both should be empty
        let repos = get_bundled_repos();
        let files = get_bundled_files();
        // Just verify the constants are well-formed (no panic)
        for (owner, repo) in repos {
            assert!(!owner.is_empty());
            assert!(!repo.is_empty());
        }
        for (path, bytes) in files {
            assert!(!path.is_empty());
            // bytes may be empty for an empty file, but path must not be empty
            let _ = bytes.len();
        }
    }
}
