name: Build and publish Cantara

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target_dir: linux
          - os: windows-latest
            target_dir: windows
          - os: macos-latest
            target_dir: macos
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Dioxus CLI
        run: cargo install dioxus-cli
      - name: Run tests
        run: cargo test
      - name: Build desktop release
        run: dx build -r
      - name: Upload desktop artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target_dir }}
          path: dist/${{ matrix.target_dir }}/
