name: Build and publish Cantara

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target_dir: linux
          - os: windows-latest
            target_dir: windows
          - os: macos-latest
            target_dir: macos
    steps:
      - name: Provide npm (needed for the build)
        uses: actions/setup-node@v4
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install cargo bininstall
        uses: cargo-bins/cargo-binstall@main
      - name: Run npm install
        run: npm install
      - name: Install dioxus-cli
        run: cargo binstall dioxus-cli
      - name: Install dependencies under Linux
        if: matrix.os == 'ubuntu-latest'
        run: |-
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - name: Run tests
        run: cargo test
      - name: Build desktop release
        run: dx build -r
      - name: Upload desktop artifact (Mac OS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target_dir }}
          path: target/dx/cantara/release/macos/app/
      - name: Upload desktop artifact (Windows and Linux)
        if: matrix.os != 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target_dir }}
          path: target/dx/cantara/release/${{ matrix.target_dir }}/app/
